const SET_USER = 'SET_USER';
const SET_IS_AUTH = 'SET_IS_AUTH';

const SET_USERS = 'SET_USERS';

// const SET_FORMS = 'SET_TEMPLATES';
const SET_ITEMS = 'SET_ITEMS';

// Forms
const SET_FORMS = 'SET_FORMS';
const SET_SELECTED_FORM = 'SET_SELECTED_FORM';
const SET_SEARCH_WORD = 'SET_SEARCH_WORD';
const RESET_FORM = 'RESET_FORM';
const SET_LOADING = 'SET_LOADING';
const SET_ERROR = 'SET_ERROR';



export { SET_USER, SET_IS_AUTH, SET_USERS, SET_ITEMS, SET_FORMS, SET_SELECTED_FORM, RESET_FORM, SET_LOADING, SET_ERROR, SET_SEARCH_WORD};